name: CI

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Publish message to Camunda Cloud
      uses: jwulf/zeebe-action@master
      with:
        zeebe_address: ${{ secrets.ZEEBE_ADDRESS }}
        zeebe_client_id: ${{ secrets.ZEEBE_CLIENT_ID }}
        zeebe_authorization_server_url: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
        zeebe_client_secret: ${{ secrets.ZEEBE_CLIENT_SECRET }}
        operation: publishMessage
        message_name: ${{ github.event.client_payload.message_name }}
        variables: ${{ github.event.client_payload.variables }}
